# -*- coding: utf-8 -*-
"""automate_Chellyne.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDXCoKTG8X01KiU_-jjAXujNn2_G-Ryc
"""

import os
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def run_preprocessing():
    print("=== MEMULAI AUTOMATION PIPELINE (LOKAL) ===")

    # 1. DATA LOADING (Membaca folder dataset dari PC lokal)
    try:
        df_user = pd.read_csv('../Dataset Indonesia Tourism Destination/user.csv')
        df_rating = pd.read_csv('../Dataset Indonesia Tourism Destination/tourism_rating.csv')
        df_tourism = pd.read_csv('../Dataset Indonesia Tourism Destination/tourism_with_id.csv')
        print("-> Sukses memuat seluruh dataset mentah.")
    except FileNotFoundError as e:
        print(f"\n[ERROR] File tidak ditemukan: {e}")
        print("Pastikan terminal kamu sudah berada di dalam folder 'preprocessing' sebelum menjalankan skrip.\n")
        return

    # 2. MULTI-TABLE JOIN
    df_merged = pd.merge(df_rating, df_tourism, on='Place_Id', how='inner')
    df_main = pd.merge(df_merged, df_user, on='User_Id', how='inner')

    # 3. HANDLING COLUMN DROPS (Pembersihan Kolom Rusak di Awal)
    kolom_sampah = ['Unnamed: 11', 'Unnamed: 12', 'Coordinate', 'Time_Minutes']
    df_drop_cols = df_main.drop(columns=kolom_sampah, errors='ignore')

    # 4. DROPPING MISSING VALUES & DUPLICATES
    df_cleaned = df_drop_cols.dropna().drop_duplicates()

    # 5. AGE BINNING (Pengelompokan Data Usia)
    age_bins = [0, 18, 30, 50, 100]
    age_labels = ['Anak-anak', 'Remaja_DewasaMuda', 'Dewasa', 'Lansia']
    df_cleaned['Age_Group'] = pd.cut(df_cleaned['Age'], bins=age_bins, labels=age_labels)

    # 6. CATEGORICAL ENCODING
    encoder = LabelEncoder()
    categorical_cols = ['Category', 'City', 'Age_Group']
    for col in categorical_cols:
        df_cleaned[f'{col}_Encoded'] = encoder.fit_transform(df_cleaned[col])

    # 7. FEATURE SCALING (MinMax Scaling pada Harga Tiket)
    df_cleaned['Price_Scaled'] = (df_cleaned['Price'] - df_cleaned['Price'].min()) / (df_cleaned['Price'].max() - df_cleaned['Price'].min())

    # 8. FEATURE SELECTION (Membuang Kolom Teks Asli)
    drop_text_cols = ['Place_Name', 'Description', 'Category', 'City', 'Location', 'Age', 'Age_Group']
    df_final = df_cleaned.drop(columns=drop_text_cols, errors='ignore')

    # 9. EXPORT DATASET SIAP LATIH KE FOLDER TUJUAN
    output_dir = 'tourism_preprocessing'
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, 'tourism_preprocessing.csv')
    df_final.to_csv(output_path, index=False)

    print("\n=== PIPELINE AUTOMATION SUCCESS ===")
    print(f"Dataset berhasil diproses otomatis dan disimpan di : {output_path}")
    print(f"Dimensi akhir data siap latih                       : {df_final.shape}")
    print(f"Total baris data siap latih                         : {df_final.shape[0]} baris")
    print(f"Total kolom data siap latih                         : {df_final.shape[1]} kolom")

if __name__ == '__main__':
    run_preprocessing()