# -*- coding: utf-8 -*-
"""modeling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMA0jBaG0ktftzMH-4n-rnyPQu9kWvia
"""


import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import mlflow

# 1. Mengaktifkan fitur Autolog dari MLflow (Syarat Kriteria Basic)
mlflow.autolog()

# Mengatur lokasi penyimpanan lokal log eksperimen MLflow
# mlflow.set_tracking_uri("file:./mlruns")
# mlflow.set_experiment("Eksperimen_SML_Basic")

def train_model():
    # 2. Memuat dataset hasil preprocessing kemarin
    # Pastikan file 'tourism_preprocessed.csv' sudah kamu unggah di session storage Colab
    if not os.path.exists('tourism_preprocessed.csv'):
        raise FileNotFoundError("Berkas tourism_preprocessed.csv tidak ditemukan! Silakan unggah terlebih dahulu.")

    df = pd.read_csv('tourism_preprocessed.csv')

    # Pisahkan Fitur (X) dan Target (y)
    # Sesuaikan 'Category' dengan nama kolom target klasifikasi di datasetmu jika berbeda
    X = df.drop(columns=['Category_Encoded'])
    y = df['Category_Encoded']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # 3. Melatih Model Klasifikasi Tanpa Tuning Hyperparameter (Sesuai Kriteria Basic)
    print("Memulai pencatatan eksperimen ke MLflow...")
    with mlflow.start_run(run_name="Random_Forest_Basic"):
        # Menggunakan model dasar Scikit-Learn
        model = RandomForestClassifier(random_state=42)
        model.fit(X_train, y_train)

        # Evaluasi performa dasar
        train_acc = model.score(X_train, y_train)
        test_acc = model.score(X_test, y_test)

        print(f"Model berhasil dilatih!")
        print(f"Akurasi Data Training: {train_acc:.4f}")
        print(f"Akurasi Data Testing : {test_acc:.4f}")

if __name__ == "__main__":
    train_model()