# -*- coding: utf-8 -*-
"""modeling_tuning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lEY534VPGaVLnwZ_37Lu29g6Vq3pxiTF
"""

import os
import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

mlflow.autolog(disable=True)

# Mengatur lokasi penyimpanan lokal log eksperimen MLflow khusus tingkatan Skilled
mlflow.set_tracking_uri("file:./mlruns")
mlflow.set_experiment("Eksperimen_SML_Skilled")

def train_tuning():
    # 2. Memuat dataset hasil preprocessing kemarin
    if not os.path.exists('tourism_preprocessed.csv'):
        raise FileNotFoundError("Berkas tourism_preprocessed.csv tidak ditemukan! Silakan unggah terlebih dahulu.")

    df = pd.read_csv('tourism_preprocessed.csv')

    # Pisahkan Fitur (X) dan Target (y) sesuai dengan kode basic kamu
    X = df.drop(columns=['Category_Encoded'])
    y = df['Category_Encoded']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # 3. Mendefinisikan kombinasi parameter untuk Hyperparameter Tuning (Kriteria Skilled)
    param_grid = {
        'n_estimators': [50, 100],
        'max_depth': [5, 10, None],
        'min_samples_split': [2, 5]
    }

    base_model = RandomForestClassifier(random_state=42)

    print("Memulai proses Hyperparameter Tuning dengan GridSearchCV...")
    # Proses pencarian kombinasi parameter terbaik
    grid_search = GridSearchCV(estimator=base_model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X_train, y_train)

    # Mengambil model terbaik dan parameter terbaik hasil tuning
    best_model = grid_search.best_estimator_
    best_params = grid_search.best_params_

    # 4. Evaluasi performa model terbaik secara manual
    y_pred_train = best_model.predict(X_train)
    y_pred_test = best_model.predict(X_test)

    train_acc = accuracy_score(y_train, y_pred_train)
    test_acc = accuracy_score(y_test, y_pred_test)
    test_prec = precision_score(y_test, y_pred_test, average='macro', zero_division=0)
    test_rec = recall_score(y_test, y_pred_test, average='macro', zero_division=0)
    test_f1 = f1_score(y_test, y_pred_test, average='macro', zero_division=0)

    print("Hyperparameter Tuning Selesai!")
    print(f"Parameter Terbaik: {best_params}")
    print(f"Akurasi Data Training: {train_acc:.4f}")
    print(f"Akurasi Data Testing : {test_acc:.4f}")

    # 5. Menerapkan Manual Logging ke MLflow (Wajib untuk tingkat Skilled)
    print("Mencatat eksperimen secara manual ke MLflow...")
    with mlflow.start_run(run_name="Random_Forest_Tuning"):
        # Log parameter terbaik secara manual
        for param_name, param_value in best_params.items():
            mlflow.log_param(param_name, param_value)

        # Log seluruh metrik evaluasi secara manual (Metrik wajib yang setara dengan autolog)
        mlflow.log_metric("train_accuracy", train_acc)
        mlflow.log_metric("test_accuracy", test_acc)
        mlflow.log_metric("test_precision", test_prec)
        mlflow.log_metric("test_recall", test_rec)
        mlflow.log_metric("test_f1_score", test_f1)

        # Menyimpan berkas biner model (artefak) secara manual ke folder 'model'
        mlflow.sklearn.log_model(best_model, "model")

        print("Berhasil menyimpan log parameter, metrik, dan artefak secara manual ke MLflow UI!")

if __name__ == "__main__":
    train_tuning()