# -*- coding: utf-8 -*-
"""modelling_tuning_advanced

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiSqavrEwiQyweiCClmO6QyVaqfJwqRO
"""



import os
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
import mlflow
import mlflow.sklearn
import dagshub

mlflow.autolog(disable=True)

dagshub.init(repo_owner='chellyneee', repo_name='Eksperimen_SML_Chellyne', mlflow=True)

def train_tuning_advance():
    # Memuat dataset hasil preprocessing kemarin
    if not os.path.exists('tourism_preprocessed.csv'):
        raise FileNotFoundError("Berkas tourism_preprocessed.csv tidak ditemukan!")

    df = pd.read_csv('tourism_preprocessed.csv')

    # Pisahkan Fitur (X) dan Target (y)
    X = df.drop(columns=['Category_Encoded'])
    y = df['Category_Encoded']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Definisikan Hyperparameter Tuning
    param_grid = {
        'n_estimators': [50, 100],
        'max_depth': [5, 10, None],
        'min_samples_split': [2, 5]
    }

    base_model = RandomForestClassifier(random_state=42)

    print("Memulai proses Hyperparameter Tuning dengan GridSearchCV (Advance)...")
    grid_search = GridSearchCV(estimator=base_model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X_train, y_train)

    best_model = grid_search.best_estimator_
    best_params = grid_search.best_params_

    # Evaluasi Performa
    y_pred_train = best_model.predict(X_train)
    y_pred_test = best_model.predict(X_test)

    train_acc = accuracy_score(y_train, y_pred_train)
    test_acc = accuracy_score(y_test, y_pred_test)
    test_prec = precision_score(y_test, y_pred_test, average='macro', zero_division=0)
    test_rec = recall_score(y_test, y_pred_test, average='macro', zero_division=0)
    test_f1 = f1_score(y_test, y_pred_test, average='macro', zero_division=0)

    print("Hyperparameter Tuning Selesai!")
    print(f"Akurasi Testing : {test_acc:.4f}")

    # ✨ Pembuatan Artefak Tambahan 1: Grafik Confusion Matrix
    cm = confusion_matrix(y_test, y_pred_test)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot(cmap=plt.cm.Blues)

    # Simpan plot secara lokal sementara waktu sebelum diunggah
    plot_path = "confusion_matrix.png"
    plt.savefig(plot_path)
    plt.close()
    print("Berhasil membuat file grafik Confusion Matrix lokal.")

    # 🚀 Menerapkan Manual Logging ke MLflow DagsHub Online
    print("Mencatat eksperimen secara online ke DagsHub...")
    with mlflow.start_run(run_name="Random_Forest_Advance"):
        # 1. Log parameter hasil tuning
        for param_name, param_value in best_params.items():
            mlflow.log_param(param_name, param_value)

        # 2. Log seluruh metrik evaluasi
        mlflow.log_metric("train_accuracy", train_acc)
        mlflow.log_metric("test_accuracy", test_acc)
        mlflow.log_metric("test_precision", test_prec)
        mlflow.log_metric("test_recall", test_rec)
        mlflow.log_metric("test_f1_score", test_f1)

        # 3. Log Artefak Utama: Model biner berekstensi .pkl
        mlflow.sklearn.log_model(best_model, "model")

        # 4. Log Artefak Tambahan 1: File Gambar Plot Evaluasi
        mlflow.log_artifact(plot_path, artifact_path="evaluation_plots")

        # 5. Log Artefak Tambahan 2: File Mentah Dataset Preprocessed yang digunakan
        mlflow.log_artifact('tourism_preprocessed.csv', artifact_path="raw_data")

        print("Berhasil menyimpan parameter, metrik, dan MINIMAL 2 ARTEFAK TAMBAHAN ke DagsHub!")

    # Bersihkan file plot lokal setelah diunggah ke cloud
    if os.path.exists(plot_path):
        os.remove(plot_path)

if __name__ == "__main__":
    train_tuning_advance()